# Generated by Django 2.2.28 on 2023-03-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
